server.port=8080
# ======================
# ???OpenAI ?????
# ======================
spring.ai.openai.base-url=https://dashscope.aliyuncs.com
spring.ai.openai.api-key=
spring.ai.openai.chat.options.model=qwen-plus
spring.ai.openai.chat.completions-path=/compatible-mode/v1/chat/completions

#------------------------------
ollama.base-url=http://localhost:11434
ollama.model.embed=bge-m3:latest
ollama.timeout-ms=60000

# ===== ???????=====
spring.datasource.url=jdbc:postgresql://localhost:5432/ai_test
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver


# ======================
# MCP Client?Spring AI 2.0?
# ======================
spring.ai.mcp.client.enabled=true
spring.ai.mcp.client.name=search
spring.ai.mcp.client.version=1.0.0

spring.ai.mcp.client.streamable-http.connections.search.url=http://localhost:8000/mcp
spring.ai.mcp.client.type=SYNC
logging.level.org.springframework.ai.mcp=DEBUG
logging.level.org.springframework.ai.chat.client=TRACE

mcp.server.url=http://localhost:8000/mcp

# ???????? 8?
spring.task.execution.pool.core-size=5
# ???????? Integer.MAX_VALUE??????
spring.task.execution.pool.max-size=20
# ??????? Integer.MAX_VALUE??????
spring.task.execution.pool.queue-capacity=100
# ??????????? 60s?
spring.task.execution.pool.keep-alive=60s
# ???????????????????
spring.task.execution.thread-name-prefix=async-task-

#rabbitmq
spring.rabbitmq.host=192.168.253.128
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.virtual-host=/

spring.rabbitmq.requested-heartbeat=30s
spring.rabbitmq.connection-timeout=5s

spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true

spring.rabbitmq.template.mandatory=true
spring.rabbitmq.template.receive-timeout=5000

spring.rabbitmq.listener.simple.concurrency=5
spring.rabbitmq.listener.simple.max-concurrency=20
spring.rabbitmq.listener.simple.prefetch=50
spring.rabbitmq.listener.simple.default-requeue-rejected=false
spring.rabbitmq.listener.simple.acknowledge-mode=manual

spring.rabbitmq.listener.simple.retry.enabled=true
